In [10]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [12]:
data={
    "trans_id":[1,2,3,4,5],
    "items":["milk,bread,eggs","butter,bread","eggs,milk","milk,bread","milk,butter"]
}
df=pd.DataFrame(data)
df

   trans_id            items
0         1  milk,bread,eggs
1         2     butter,bread
2         3        eggs,milk
3         4       milk,bread
4         5      milk,butter

In [ ]:
#Encoding

In [14]:
transactions=df['items'].apply(lambda x:x.split(','))
te=TransactionEncoder()

In [16]:
te_data=te.fit(transactions).transform(transactions)
te_encoded=pd.DataFrame(te_data,columns=te.columns_)

In [17]:
te_encoded.head()

   bread  butter   eggs   milk
0   True   False   True   True
1   True    True  False  False
2  False   False   True   True
3   True   False  False   True
4  False    True  False   True

In [ ]:
# Apriori Algorithm

In [19]:
freq_itemsets=apriori(te_encoded,min_support=0.2,use_colnames=True)

In [ ]:
#Association Rule Mining

In [21]:
rules=association_rules(freq_itemsets,metric="confidence",min_threshold=0.5)

In [23]:
print("Association Rules")
print(rules[['antecedents','consequents','support','confidence','lift']])

Association Rules
      antecedents    consequents  support  confidence      lift
0        (butter)        (bread)      0.2    0.500000  0.833333
1          (eggs)        (bread)      0.2    0.500000  0.833333
2          (milk)        (bread)      0.4    0.500000  0.833333
3         (bread)         (milk)      0.4    0.666667  0.833333
4        (butter)         (milk)      0.2    0.500000  0.625000
5          (milk)         (eggs)      0.4    0.500000  1.250000
6          (eggs)         (milk)      0.4    1.000000  1.250000
7   (milk, bread)         (eggs)      0.2    0.500000  1.250000
8    (milk, eggs)        (bread)      0.2    0.500000  0.833333
9   (bread, eggs)         (milk)      0.2    1.000000  1.250000
10         (eggs)  (milk, bread)      0.2    0.500000  1.250000

In [ ]:
# Conclusion
#{eggs}->{milk}
#{